# Generated by Django 5.2.17 on 2026-08-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_ai_analysis_and_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.TextField(help_text='Comma-separated, e.g. Python, Django, SQL'),
        ),
    ]
