# Generated by Django 6.0.7 on 2026-09-03 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_skill_gap_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_app_job_status_applied_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_app_candidate_status_idx',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_app_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status'], name='jobs_app_cand_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-applied_at'], name='jobs_app_status_applied_idx'),
        ),
    ]
