# Generated by Django 6.0.7 on 2026-09-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidate_skill_cache'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidateprofile',
            name='accounts_candidate_updated_idx',
        ),
    ]
